### ISSUE TITLE
Compilation error in iOS on upgrading from version 5.0.0 to any of 6.0.x

### ISSUE THREAD

**Issue by mspnr** [kineapps/flutter_archive#81]
After upgrading version in `pubspec.yaml`
from `flutter_archive: ^5.0.0` to `flutter_archive: ^6.0.0` I am getting a compilation error:

Part from the middle
```
    [!] CocoaPods could not find compatible versions for pod "ZIPFoundation":
      In snapshot (Podfile.lock):
        ZIPFoundation (= 0.9.13)

      In Podfile:
        flutter_archive (from `.symlinks/plugins/flutter_archive/ios`) was resolved to 0.0.1, which depends on
          ZIPFoundation (= 0.9.19)

    Specs satisfying the `ZIPFoundation (= 0.9.13), ZIPFoundation (= 0.9.19)` dependency were found, but they required a higher minimum deployment target.
```

Part from the end:
```
Error: The pod "ZIPFoundation" required by the plugin "flutter_archive" requires a higher minimum iOS deployment version than the plugin's reported minimum version.
To build, remove the plugin "flutter_archive", or contact the plugin's developers for assistance.
Error running pod install
```

When using 5.0.0 no error is coming on iOS and the app is working all right.  None of 6.0.x is compiling.
Android is building and working in version 6.0.3 all right.

My versions are:
Flutter 3.22.1
XCode 15.4
iOS platform 17.5

**Comment by lxhlzyh** [comment]
Same, Cocoapods can not found the version.https://cocoapods.org/pods/ZIPFoundation#changelog
Roll to 5.0.0 can solve.Waitting cocoapods update?

**Comment by kinex** [comment]
Not sure what is the problem since I don't have this issue. Please check that the minimum iOS deployment version of your app is 12.0 or higher.

**Comment by lxhlzyh** [comment]
Here is my solution:
1.check ZIPFoundation lastest version
pod outdated

2.delete Podfile.lock or edit ZIPFoundation version(deprecated)

3.delete dir ios/Pods、ios/.symlinks

4.pod install

**Comment by mspnr** [comment]
@lxhlzyh, @kinex thank you for your hints. I tried all of them and they didn't work straight away. I searched at the Internet and tried other options. At the end the pods were updated with the latest version of the plugin 6.0.3. I think `pod update` did the trick. Thank you for your support!
