### ISSUE TITLE
Seeing build issues on Android after upgrading to 2.12.0-4.1.pre on flutter beta channel

### ISSUE THREAD

**Issue by 91jaeminjo** [kineapps/flutter_archive#52]
Below is the error message:

```
....../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_archive-4.2.0/android/src/main/kotlin/com/kineapps/flutterarchive/FlutterArchivePlugin.kt: (455, 58): 
Object is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): 
Unit defined in io.flutter.plugin.common.MethodChannel.Result
```

I don't see this issue on ios.

This issue is preventing me to build on Android.

is there a fix/workaround for the issue?

**Comment by luomo-pro** [comment]
I have the same problem, is there a solution now?

**Comment by curonny** [comment]
me too!! I have the same problem

**Comment by kinex** [comment]
Fixed in https://github.com/kineapps/flutter_archive/commit/03531b8f13d2fc19f800a34f8a80e442ba06e056
